# -*- coding: utf-8 -*-
"""2.1사진천장 사이즈 한번에 변경.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AWok3uoJFSshFzDe-GsRG1husePBYU4n

#파이썬 기술 살펴보기

PIL open
"""

from PIL import Image
a = Image.open('cat.jpg')

"""image size"""

x,y = a.size
print(x,y)




"""resize"""
b = a.resize((200,300))

print(b)



b.show()




"""save"""

